### ISSUE TITLE
When running ./quickstart-setup-store.sh test I recieve the following error

### ISSUE THREAD

**Issue by itsallrelative** [forcedotcom/b2b-commerce-on-lightning-quickstart#1]
`ERROR running force:data:tree:import:  {"hasErrors":true,"results":[{"referenceId":"PricebookEntryRef2","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef4","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef6","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef8","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef10","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef12","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef14","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef16","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef18","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef20","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef22","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef24","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef26","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef28","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef30","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef32","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]},{"referenceId":"PricebookEntryRef34","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Pricebook2Id]","fields":["Pricebook2Id"]}]}]}
5. Mapping Admin User to Role.
ERROR running force:data:record:update:  An unexpected error occurred. Please include this ErrorId if you contact support: 1677524363-167767 (2074184818)
6. Creating Buyer User with associated Contact and Account.
ERROR running force:user:create:  Insert failed. First exception on row 0; first error: UNKNOWN_EXCEPTION, portal account owner must have a role: []
Making Account a Buyer Account.
ERROR running force:data:record:create:  Required fields are missing: [BuyerId]
Assigning Buyer Account to Buyer Group.
ERROR running force:data:record:create:  Required fields are missing: [BuyerId]`

**Comment by cnastasa** [comment]
@itsallrelative thank you for letting us know about this! The errors you mention should now be fixed or worked around. Please try again with a new scratch org.
