### ISSUE TITLE
Scratch Org Error on Creation - Commerce does not exist. 

### ISSUE THREAD

**Issue by samphif** [forcedotcom/b2b-commerce-on-lightning-quickstart#30]
After testing multiple times to setup a scratch org I've received this message. 

Command:
> sfdx force:org:create -f config/project-scratch-def.json username=sam+commerce1@gmail.com` -s -d 15

Error: 
> === Component Failures [1]
TYPE   FILE               NAME  PROBLEM
Error  shape/package.xml        The object 'Commerce' of type Settings metadata does not exist.

at the  same time the scratch org IS created, but when I continue to the next step and run + provide a store name. This error continues to repeat every 10 seconds. 

Command: 
> ./quickstart-create-and-setup-store.sh

Error: 
>ERROR at Row:1:Column:16
sObject type 'WebStore' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
Store not yet created, waiting 10 seconds...
Querying Data... done
ERROR running force:data:soql:query:  
SELECT Id FROM WebStore WHERE Name='scratchstore'

Outcome: 
A scratch org exists but no store is created

**Comment by samphif** [comment]
Per some other Issues, I've also tested switching down to the Spring 21 Branch vs the Master Branch to copy from and receive the same 
>The object 'Commerce' of type Settings metadata does not exist.

**Comment by WarbleSync** [comment]
Yes I'm seeing the same issue

**Comment by raffaeledesimone** [comment]
> After testing multiple times to setup a scratch org I've received this message.
> 
> Command:
> 
> > sfdx force:org:create -f config/project-scratch-def.json username=[sam+commerce1@gmail.com](mailto:sam+commerce1@gmail.com)` -s -d 15
> 
> Error:
> 
> > === Component Failures [1]
> > TYPE   FILE               NAME  PROBLEM
> > Error  shape/package.xml        The object 'Commerce' of type Settings metadata does not exist.
> 
> at the same time the scratch org IS created, but when I continue to the next step and run + provide a store name. This error continues to repeat every 10 seconds.
> 
> Command:
> 
> > ./quickstart-create-and-setup-store.sh
> 
> Error:
> 
> > ERROR at Row:1:Column:16
> > sObject type 'WebStore' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
> > Store not yet created, waiting 10 seconds...
> > Querying Data... done
> > ERROR running force:data:soql:query:
> > SELECT Id FROM WebStore WHERE Name='scratchstore'
> 
> Outcome:
> A scratch org exists but no store is created

I have resolved the error removing this setting from `config/project-scratch-def.json`:
`,
    "commerceSettings": {
      "commerceEnabled": true
  }`

**Comment by samphif** [comment]
@raffaeledesimone the current org version is api version 51.0 i've tried running the command with 52 but that isn't allowed, switching to run apiversion=51 returns the same issue. do i need to 



> Samuels-MacBook-Pro:sfdx samuelphifer$ sfdx force:org:create -f config/project-scratch-def.json username=samphif+commerce4@gmail.com --apiversion=51.0 -s -d 15
=== Component Failures [1]
TYPE   FILE               NAME  PROBLEM
─────  ─────────────────  ────  ───────────────────────────────────────────────────────────────
Error  shape/package.xml        The object 'Commerce' of type Settings metadata does not exist.
=== Component Failures [1]
TYPE   FILE               NAME  PROBLEM
─────  ─────────────────  ────  ───────────────────────────────────────────────────────────────
Error  shape/package.xml        The object 'Commerce' of type Settings metadata does not exist.
ERROR running force:org:create:  Failed to deploy settings to scratch org.

**Comment by raffaeledesimone** [comment]
> @raffaeledesimone the current org version is api version 51.0 i've tried running the command with 52 but that isn't allowed, switching to run apiversion=51 returns the same issue.
> 
> > Samuels-MacBook-Pro:sfdx samuelphifer$ sfdx force:org:create -f config/project-scratch-def.json username=[samphif+commerce4@gmail.com](mailto:samphif+commerce4@gmail.com) --apiversion=51.0 -s -d 15
> > === Component Failures [1]
> > TYPE   FILE               NAME  PROBLEM
> > ─────  ─────────────────  ────  ───────────────────────────────────────────────────────────────
> > Error  shape/package.xml        The object 'Commerce' of type Settings metadata does not exist.
> > === Component Failures [1]
> > TYPE   FILE               NAME  PROBLEM
> > ─────  ─────────────────  ────  ───────────────────────────────────────────────────────────────
> > Error  shape/package.xml        The object 'Commerce' of type Settings metadata does not exist.
> > ERROR running force:org:create:  Failed to deploy settings to scratch org.

Sorry, i think you have to wait that salsforce update your org instance to version 52.0

**Comment by AshRelateIQ** [comment]
@samphif the need for a Commerce setting in the project-scratch-def.json file applies to orgs with api version = 52.0 and over. If your org is api version 51.0,  the spring21 branch will have the correct project scratch def [link](https://github.com/forcedotcom/b2b-commerce-on-lightning-quickstart/blob/spring21/sfdx/config/project-scratch-def.json). If the same error persists, it may be because your project-scratch-def file still has the "commerceSettings" tag.

**Comment by samphif** [comment]
awesome I just signed up for a summer 21 release preview and this works like a charm. thanks for the assist
