### ISSUE TITLE
Error while trying to run ./quickstart-setup-store.sh to Create store in Scratchorg

### ISSUE THREAD

**Issue by riyazms07** [forcedotcom/b2b-commerce-on-lightning-quickstart#40]
./quickstart-setup-store.sh while running this command to create B2B Commerce Store in Scratch ogr from Visual studio code , i get error "C;/Program is not recognized as an internal or external command ,operable or batch file " 
I have set up path envronment variables , C:\Program Files\Git\Cmd but error still not resolved . Please advise how to resolve this error

**Comment by riyazms07** [comment]
reinstalled all supporting tools to C:\User  folder

**Comment by TinXC** [comment]
Is this resolved?

**Comment by AlexSitnikSF** [comment]
@riyazms07 Could you please clarify what you meant by 'all supporting tools'? I stumbled upon the same problem on Win 10, even tried using WSL with Ubuntu, but with no luck.
