### ISSUE TITLE
Can't push data to the scratch org (flow error's)

### ISSUE THREAD

**Issue by mauriciomoita** [forcedotcom/b2b-commerce-on-lightning-quickstart#7]
Hello everyone, first of all, thank you for giving us a project to set up a store and try it out!

When I try to push data to scratch org I'm getting the error "Invalid version specified:51.0" so I've changed the sfdx-project.json file to "sourceApiVersion": "50.0" and all XML files to <apiVersion>50.0</apiVersion>, now when I run the push command I'm getting those errors: 

- "Error  force-app\main\default\flows\Process_CommerceDiagnosticEvents.flow-meta.xml      Error parsing file: Element {http://soap.sforce.com/2006/04/metadata}flowTransactionModel invalid at this location in type FlowActionCall (19:31)
- Error  force-app\main\default\flows\Spring_2021_Subflow_Delivery_Method.flow-meta.xml   Error parsing file: 'setCheckoutDeliveryMethod' is not a valid value for the 
enum 'InvocableActionType' (19:59)
- Error  force-app\main\default\flows\Spring_2021_Subflow_Checkout_Summary.flow-meta.xml  deliveryMethod (Screen Component) - We can't find this input attribute: "isReadOnly".
- Error  force-app\main\default\flows\Spring_2021_Checkout.flow-meta.xml                  Delivery_Method (Subflow) - The flow Spring_2021_Subflow_Delivery_Method doesn't exist.

ERROR running force:source:push:  Push failed."

Maybe it's related to the org version, I don't really know.

Could you help, please?

**Comment by smolynsf** [comment]
Hi Mauricio,
you are right in assuming it is related to the org version.
Currently our master branch has been updated to match the Spring21 release, which I think is only just now starting to show up in sandbox environments.  

If you are working against the Winter21 release (api version 50), please switch to the winter21 branch.

**Comment by mauriciomoita** [comment]
Hi! Thank you for your reply!

Ok, I will try with that branch. Just to be clear, is that one -> https://github.com/achabrol/b2b-commerce-on-lightning-quickstart ?

**Comment by mauriciomoita** [comment]
Definitely worked for me. Thanks
